[package]
name = "postmark"
description = "Postmark rust client"
license = "MIT/Apache-2.0"
authors = ["Pierre-Alexandre St-Jean <pa@braver.health>"]
repository = "https://github.com/braverhealth/postmark-rust"
homepage = "https://github.com/braverhealth/postmark-rust"
documentation = "https://docs.rs/postmark"
keywords = ["postmark", "email", "e-mail", "http"]
readme = "README.md"
categories = ["api-bindings", "email", "web-programming::http-client"]
version = "0.1.1-alpha.0"
edition = "2018"

[dependencies]
async-trait = "0.1.50"
reqwest = { version = "0.11", features = ["json"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
typed-builder = "0.9.0"

[features]
default = ["reqwest-client"]
reqwest-client=["reqwest"]
